name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.2.0
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: npm run build:docker      
      
    - name: Tag the Docker image
      run: docker tag nodejsstarter thehaseebahmed/nodejs-starter
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: thehaseebahmed/nodejs-typescript-starter
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: docker push thehaseebahmed/nodejs-starter
